import type { LucideIcon } from 'lucide-react';

export type TemplateField = {
  name: string;
  label: string;
  placeholder: string;
  type: 'text' | 'textarea' | 'date';
  required?: boolean;
};

export type Template = {
  id: string;
  name: string;
  description: string;
  icon: string;
  fields: TemplateField[];
};

export const templates: Template[] = [
  {
    id: 'nda',
    name: 'Non-Disclosure Agreement',
    description: 'A contract to protect confidential information shared between parties.',
    icon: 'FileLock',
    fields: [
      { name: 'disclosingParty', label: 'Disclosing Party Name', placeholder: 'e.g., InnovateCorp', type: 'text', required: true },
      { name: 'receivingParty', label: 'Receiving Party Name', placeholder: 'e.g., Partner Solutions LLC', type: 'text', required: true },
      { name: 'effectiveDate', label: 'Effective Date', placeholder: '', type: 'date', required: true },
      { name: 'term', label: 'Term of Agreement (in years)', placeholder: 'e.g., 5', type: 'text', required: true },
      { name: 'confidentialInfo', label: 'Description of Confidential Information', placeholder: 'e.g., Business plans, financial data, customer lists', type: 'textarea', required: true },
    ],
  },
  {
    id: 'service-agreement',
    name: 'Service Agreement',
    description: 'An agreement outlining the terms of a service provided by one party to another.',
    icon: 'Briefcase',
    fields: [
      { name: 'serviceProvider', label: 'Service Provider', placeholder: 'e.g., Your Company LLC', type: 'text', required: true },
      { name: 'client', label: 'Client Name', placeholder: 'e.g., Client Corp', type: 'text', required: true },
      { name: 'serviceDescription', label: 'Description of Services', placeholder: 'e.g., Web development and design services', type: 'textarea', required: true },
      { name: 'paymentAmount', label: 'Payment Amount ($)', placeholder: 'e.g., 5000', type: 'text', required: true },
      { name: 'paymentTerms', label: 'Payment Terms', placeholder: 'e.g., Net 30, 50% upfront', type: 'text', required: true },
      { name: 'startDate', label: 'Start Date', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'employment-contract',
    name: 'Employment Contract',
    description: 'Defines the terms of employment between an employer and an employee.',
    icon: 'Users',
    fields: [
      { name: 'employer', label: 'Employer Name', placeholder: 'e.g., Growth Inc.', type: 'text', required: true },
      { name: 'employee', label: 'Employee Name', placeholder: 'e.g., Jane Doe', type: 'text', required: true },
      { name: 'jobTitle', label: 'Job Title', placeholder: 'e.g., Software Engineer', type: 'text', required: true },
      { name: 'salary', label: 'Annual Salary ($)', placeholder: 'e.g., 90000', type: 'text', required: true },
      { name: 'startDate', label: 'Employment Start Date', placeholder: '', type: 'date', required: true },
      { name: 'duties', label: 'Key Responsibilities', placeholder: 'Developing new features, maintaining codebase...', type: 'textarea' },
    ],
  },
  {
    id: 'lease-agreement',
    name: 'Residential Lease',
    description: 'A contract between a landlord and tenant for renting a property.',
    icon: 'Home',
    fields: [
      { name: 'landlord', label: 'Landlord Name', placeholder: 'e.g., John Smith', type: 'text', required: true },
      { name: 'tenant', label: 'Tenant Name', placeholder: 'e.g., Sarah Johnson', type: 'text', required: true },
      { name: 'propertyAddress', label: 'Property Address', placeholder: 'e.g., 123 Main St, Anytown, USA', type: 'text', required: true },
      { name: 'leaseStartDate', label: 'Lease Start Date', placeholder: '', type: 'date', required: true },
      { name: 'leaseEndDate', label: 'Lease End Date', placeholder: '', type: 'date', required: true },
      { name: 'rentAmount', label: 'Monthly Rent ($)', placeholder: 'e.g., 1500', type: 'text', required: true },
      { name: 'securityDeposit', label: 'Security Deposit ($)', placeholder: 'e.g., 1500', type: 'text', required: true },
    ],
  },
  {
    id: 'independent-contractor-agreement',
    name: 'Independent Contractor Agreement',
    description: 'A contract between a client and a contractor for services.',
    icon: 'FileText',
    fields: [
      { name: 'clientName', label: 'Client Name', placeholder: 'e.g., Acme Corp', type: 'text', required: true },
      { name: 'contractorName', label: 'Contractor Name', placeholder: 'e.g., John Doe', type: 'text', required: true },
      { name: 'services', label: 'Description of Services', placeholder: 'e.g., Graphic design services', type: 'textarea', required: true },
      { name: 'payment', label: 'Payment Amount ($)', placeholder: 'e.g., 2500', type: 'text', required: true },
      { name: 'projectDeadline', label: 'Project Deadline', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'partnership-agreement',
    name: 'Partnership Agreement',
    description: 'An agreement defining the rights and responsibilities of business partners.',
    icon: 'Users',
    fields: [
      { name: 'partnershipName', label: 'Partnership Name', placeholder: 'e.g., Best Buds Bakery', type: 'text', required: true },
      { name: 'partner1', label: 'Partner 1 Name', placeholder: 'e.g., Alice', type: 'text', required: true },
      { name: 'partner2', label: 'Partner 2 Name', placeholder: 'e.g., Bob', type: 'text', required: true },
      { name: 'capitalContribution1', label: 'Partner 1 Capital Contribution ($)', placeholder: 'e.g., 10000', type: 'text', required: true },
      { name: 'capitalContribution2', label: 'Partner 2 Capital Contribution ($)', placeholder: 'e.g., 10000', type: 'text', required: true },
      { name: 'profitDistribution', label: 'Profit Distribution', placeholder: 'e.g., 50/50', type: 'text', required: true },
    ],
  },
  {
    id: 'llc-operating-agreement',
    name: 'LLC Operating Agreement',
    description: 'An agreement outlining the ownership and operating procedures of an LLC.',
    icon: 'Building',
    fields: [
      { name: 'llcName', label: 'LLC Name', placeholder: 'e.g., My Awesome LLC', type: 'text', required: true },
      { name: 'stateOfFormation', label: 'State of Formation', placeholder: 'e.g., Delaware', type: 'text', required: true },
      { name: 'member1', label: 'Member 1 Name', placeholder: 'e.g., Jane Smith', type: 'text', required: true },
      { name: 'member2', label: 'Member 2 Name', placeholder: 'e.g., John Doe', type: 'text' },
      { name: 'managementStructure', label: 'Management Structure', placeholder: 'e.g., Member-Managed', type: 'text', required: true },
    ],
  },
  {
    id: 'privacy-policy',
    name: 'Privacy Policy',
    description: 'A statement that discloses how a company gathers, uses, and manages customer data.',
    icon: 'Shield',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., YourWebsite.com', type: 'text', required: true },
      { name: 'effectiveDate', label: 'Effective Date', placeholder: '', type: 'date', required: true },
      { name: 'dataCollected', label: 'Types of Data Collected', placeholder: 'e.g., Names, email addresses, cookies', type: 'textarea', required: true },
      { name: 'dataUsage', label: 'How Data Is Used', placeholder: 'e.g., To provide services, for marketing', type: 'textarea', required: true },
    ],
  },
  {
    id: 'terms-of-service',
    name: 'Terms of Service',
    description: 'The legal agreements between a service provider and a person who wants to use that service.',
    icon: 'FileText',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., YourSaaS', type: 'text', required: true },
      { name: 'websiteURL', label: 'Website URL', placeholder: 'e.g., www.yoursaas.com', type: 'text', required: true },
      { name: 'effectiveDate', label: 'Effective Date', placeholder: '', type: 'date', required: true },
      { name: 'jurisdiction', label: 'Governing Law Jurisdiction', placeholder: 'e.g., State of California, USA', type: 'text', required: true },
    ],
  },
  {
    id: 'consulting-agreement',
    name: 'Consulting Agreement',
    description: 'A contract between a consultant and a client for consulting services.',
    icon: 'Briefcase',
    fields: [
      { name: 'consultantName', label: 'Consultant Name', placeholder: 'e.g., Expert Consultants Inc.', type: 'text', required: true },
      { name: 'clientName', label: 'Client Name', placeholder: 'e.g., Data Corp', type: 'text', required: true },
      { name: 'consultingServices', label: 'Description of Services', placeholder: 'e.g., IT infrastructure consulting', type: 'textarea', required: true },
      { name: 'compensation', label: 'Compensation', placeholder: 'e.g., $150 per hour', type: 'text', required: true },
      { name: 'agreementStartDate', label: 'Start Date', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'photo-release-form',
    name: 'Photo Release Form',
    description: 'A form that grants permission to use someone\'s photograph.',
    icon: 'Camera',
    fields: [
      { name: 'photographerName', label: 'Photographer Name', placeholder: 'e.g., Pro Shots', type: 'text', required: true },
      { name: 'modelName', label: 'Model Name', placeholder: 'e.g., Alex Ray', type: 'text', required: true },
      { name: 'dateOfPhotoShoot', label: 'Date of Photoshoot', placeholder: '', type: 'date', required: true },
      { name: 'locationOfShoot', label: 'Location of Photoshoot', placeholder: 'e.g., Central Park, NYC', type: 'text', required: true },
      { name: 'compensationForRelease', label: 'Compensation for Release', placeholder: 'e.g., $100', type: 'text' },
    ],
  },
  {
    id: 'cease-and-desist-letter',
    name: 'Cease and Desist Letter',
    description: 'A letter sent to an individual or business to stop allegedly illegal activity.',
    icon: 'Gavel',
    fields: [
      { name: 'senderName', label: 'Your Name (Sender)', placeholder: 'e.g., Your Name', type: 'text', required: true },
      { name: 'recipientName', label: 'Recipient Name', placeholder: 'e.g., Infringing Party', type: 'text', required: true },
      { name: 'infringingActivity', label: 'Description of Infringing Activity', placeholder: 'e.g., Unauthorized use of copyrighted material', type: 'textarea', required: true },
      { name: 'dateOfLetter', label: 'Date of Letter', placeholder: '', type: 'date', required: true },
      { name: 'deadlineForCompliance', label: 'Deadline for Compliance', placeholder: 'e.g., 15 days', type: 'text', required: true },
    ],
  },
  {
    id: 'promissory-note',
    name: 'Promissory Note',
    description: 'A written promise to pay a specific amount of money to someone.',
    icon: 'Landmark',
    fields: [
      { name: 'lenderName', label: 'Lender Name', placeholder: 'e.g., John Smith', type: 'text', required: true },
      { name: 'borrowerName', label: 'Borrower Name', placeholder: 'e.g., Jane Doe', type: 'text', required: true },
      { name: 'principalAmount', label: 'Principal Amount ($)', placeholder: 'e.g., 1000', type: 'text', required: true },
      { name: 'interestRate', label: 'Annual Interest Rate (%)', placeholder: 'e.g., 5', type: 'text', required: true },
      { name: 'dateOfNote', label: 'Date of Note', placeholder: '', type: 'date', required: true },
      { name: 'repaymentTerms', label: 'Repayment Terms', placeholder: 'e.g., Monthly installments of $100', type: 'textarea', required: true },
    ],
  },
  {
    id: 'bill-of-sale',
    name: 'Bill of Sale',
    description: 'A document that transfers ownership of goods from one person to another.',
    icon: 'ShoppingCart',
    fields: [
      { name: 'sellerName', label: 'Seller Name', placeholder: 'e.g., Tom Seller', type: 'text', required: true },
      { name: 'buyerName', label: 'Buyer Name', placeholder: 'e.g., Betty Buyer', type: 'text', required: true },
      { name: 'itemSold', label: 'Description of Item Sold', placeholder: 'e.g., 2023 Honda Civic', type: 'textarea', required: true },
      { name: 'purchasePrice', label: 'Purchase Price ($)', placeholder: 'e.g., 25000', type: 'text', required: true },
      { name: 'dateOfSale', label: 'Date of Sale', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'offer-of-employment-letter',
    name: 'Offer of Employment Letter',
    description: 'A formal offer of employment to a candidate.',
    icon: 'Mail',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., Future Corp', type: 'text', required: true },
      { name: 'candidateName', label: 'Candidate Name', placeholder: 'e.g., Sarah Lee', type: 'text', required: true },
      { name: 'jobTitle', label: 'Job Title', placeholder: 'e.g., Marketing Manager', type: 'text', required: true },
      { name: 'annualSalary', label: 'Annual Salary ($)', placeholder: 'e.g., 75000', type: 'text', required: true },
      { name: 'startDate', label: 'Proposed Start Date', placeholder: '', type: 'date', required: true },
      { name: 'offerDeadline', label: 'Offer Acceptance Deadline', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'resignation-letter',
    name: 'Resignation Letter',
    description: 'A formal letter from an employee to their employer announcing their resignation.',
    icon: 'UserMinus',
    fields: [
      { name: 'employeeName', label: 'Your Name (Employee)', placeholder: 'e.g., Your Name', type: 'text', required: true },
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., Your Current Employer', type: 'text', required: true },
      { name: 'managerName', label: 'Manager\'s Name', placeholder: 'e.g., Your Manager', type: 'text', required: true },
      { name: 'lastDayOfEmployment', label: 'Last Day of Employment', placeholder: '', type: 'date', required: true },
      { name: 'reasonForLeaving', label: 'Reason for Leaving (Optional)', placeholder: 'e.g., Pursuing a new opportunity', type: 'textarea' },
    ],
  },
  {
    id: 'power-of-attorney',
    name: 'Power of Attorney',
    description: 'A legal document giving one person the power to act for another person.',
    icon: 'Key',
    fields: [
      { name: 'principalName', label: 'Principal Name (Grantor)', placeholder: 'e.g., John Appleseed', type: 'text', required: true },
      { name: 'agentName', label: 'Agent Name (Attorney-in-Fact)', placeholder: 'e.g., Jane Appleseed', type: 'text', required: true },
      { name: 'powersGranted', label: 'Powers Granted', placeholder: 'e.g., Financial matters, healthcare decisions', type: 'textarea', required: true },
      { name: 'effectiveDate', label: 'Effective Date', placeholder: '', type: 'date', required: true },
      { name: 'terminationDate', label: 'Termination Date (Optional)', placeholder: '', type: 'date' },
    ],
  },
  {
    id: 'last-will-and-testament',
    name: 'Last Will and Testament',
    description: 'A legal document that communicates a person\'s final wishes.',
    icon: 'Book',
    fields: [
      { name: 'testatorName', label: 'Your Name (Testator)', placeholder: 'e.g., Your Full Name', type: 'text', required: true },
      { name: 'executorName', label: 'Executor Name', placeholder: 'e.g., Name of person to carry out your will', type: 'text', required: true },
      { name: 'beneficiary1', label: 'Beneficiary 1 Name', placeholder: 'e.g., Spouse, child, etc.', type: 'text', required: true },
      { name: 'beneficiary1Inheritance', label: 'Inheritance for Beneficiary 1', placeholder: 'e.g., My house at 123 Main St', type: 'textarea', required: true },
      { name: 'beneficiary2', label: 'Beneficiary 2 Name', placeholder: '', type: 'text' },
      { name: 'beneficiary2Inheritance', label: 'Inheritance for Beneficiary 2', placeholder: '', type: 'textarea' },
    ],
  },
  {
    id: 'affidavit',
    name: 'Affidavit',
    description: 'A written sworn statement of fact voluntarily made by an affiant or deponent.',
    icon: 'FileCheck',
    fields: [
      { name: 'affiantName', label: 'Affiant Name (Your Name)', placeholder: 'e.g., Your Full Name', type: 'text', required: true },
      { name: 'statementOfFacts', label: 'Statement of Facts', placeholder: 'A detailed account of the facts as you know them.', type: 'textarea', required: true },
      { name: 'dateOfSwearing', label: 'Date of Swearing', placeholder: '', type: 'date', required: true },
      { name: 'notaryPublicName', label: 'Notary Public Name', placeholder: 'e.g., Name of Notary', type: 'text', required: true },
      { name: 'jurisdiction', label: 'Jurisdiction (e.g., State and County)', placeholder: 'e.g., County of Los Angeles, State of California', type: 'text', required: true },
    ],
  },
  {
    id: 'website-terms-and-conditions',
    name: 'Website Terms and Conditions',
    description: 'Rules by which one must agree to abide in order to use a website.',
    icon: 'Globe',
    fields: [
      { name: 'websiteName', label: 'Website Name', placeholder: 'e.g., MyAwesomeSite', type: 'text', required: true },
      { name: 'websiteUrl', label: 'Website URL', placeholder: 'e.g., www.myawesomesite.com', type: 'text', required: true },
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., Awesome Inc.', type: 'text', required: true },
      { name: 'governingLaw', label: 'Governing Law', placeholder: 'e.g., State of New York', type: 'text', required: true },
      { name: 'lastUpdatedDate', label: 'Last Updated Date', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'cookie-policy',
    name: 'Cookie Policy',
    description: 'A policy explaining what cookies are active on a website and what user data they track.',
    icon: 'Cookie',
    fields: [
      { name: 'websiteName', label: 'Website Name', placeholder: 'e.g., MyWebsite', type: 'text', required: true },
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., My Company Inc.', type: 'text', required: true },
      { name: 'typesOfCookies', label: 'Types of Cookies Used', placeholder: 'e.g., Session, Persistent, Third-Party', type: 'textarea', required: true },
      { name: 'dataCollected', label: 'Data Collected by Cookies', placeholder: 'e.g., IP address, browsing history', type: 'textarea', required: true },
      { name: 'policyEffectiveDate', label: 'Policy Effective Date', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'rental-application',
    name: 'Rental Application',
    description: 'A form used by landlords to screen potential tenants.',
    icon: 'ClipboardList',
    fields: [
      { name: 'applicantName', label: 'Applicant Full Name', placeholder: 'e.g., Jane Doe', type: 'text', required: true },
      { name: 'currentAddress', label: 'Current Address', placeholder: 'e.g., 456 Oak Ave, Anytown', type: 'text', required: true },
      { name: 'employerName', label: 'Employer Name', placeholder: 'e.g., Acme Corporation', type: 'text', required: true },
      { name: 'monthlyIncome', label: 'Monthly Income ($)', placeholder: 'e.g., 4000', type: 'text', required: true },
      { name: 'propertyAddress', label: 'Rental Property Address', placeholder: 'e.g., 123 Main St, Anytown', type: 'text', required: true },
    ],
  },
  {
    id: 'eviction-notice',
    name: 'Eviction Notice',
    description: 'A formal letter from a landlord to a tenant to vacate a property.',
    icon: 'Home',
    fields: [
      { name: 'landlordName', label: 'Landlord Name', placeholder: 'e.g., John Landlord', type: 'text', required: true },
      { name: 'tenantName', label: 'Tenant Name', placeholder: 'e.g., Bad Tenant', type: 'text', required: true },
      { name: 'propertyAddress', label: 'Property Address', placeholder: 'e.g., 123 Main St, Anytown', type: 'text', required: true },
      { name: 'reasonForEviction', label: 'Reason for Eviction', placeholder: 'e.g., Non-payment of rent', type: 'textarea', required: true },
      { name: 'noticeDate', label: 'Date of Notice', placeholder: '', type: 'date', required: true },
      { name: 'vacateDate', label: 'Date to Vacate By', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'loan-agreement',
    name: 'Loan Agreement',
    description: 'A contract between a borrower and a lender which formalizes the loan process.',
    icon: 'Landmark',
    fields: [
      { name: 'lenderName', label: 'Lender Name', placeholder: 'e.g., First National Bank', type: 'text', required: true },
      { name: 'borrowerName', label: 'Borrower Name', placeholder: 'e.g., John Borrower', type: 'text', required: true },
      { name: 'loanAmount', label: 'Loan Amount ($)', placeholder: 'e.g., 10000', type: 'text', required: true },
      { name: 'interestRate', label: 'Annual Interest Rate (%)', placeholder: 'e.g., 7.5', type: 'text', required: true },
      { name: 'loanTerm', label: 'Loan Term (in months)', placeholder: 'e.g., 60', type: 'text', required: true },
      { name: 'loanDate', label: 'Date of Loan', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'demand-letter-for-payment',
    name: 'Demand Letter for Payment',
    description: 'A formal letter demanding payment of a debt.',
    icon: 'FileWarning',
    fields: [
      { name: 'creditorName', label: 'Your Name (Creditor)', placeholder: 'e.g., Your Name or Company', type: 'text', required: true },
      { name: 'debtorName', label: 'Debtor Name', placeholder: 'e.g., Person who owes money', type: 'text', required: true },
      { name: 'amountOwed', label: 'Amount Owed ($)', placeholder: 'e.g., 500', type: 'text', required: true },
      { name: 'reasonForDebt', label: 'Reason for Debt', placeholder: 'e.g., Unpaid invoice #123', type: 'textarea', required: true },
      { name: 'paymentDeadline', label: 'Payment Deadline', placeholder: 'e.g., 30 days from date of letter', type: 'text', required: true },
    ],
  },
  {
    id: 'release-of-liability-waiver',
    name: 'Release of Liability (Waiver)',
    description: 'A legal document that releases one party from liability.',
    icon: 'ShieldCheck',
    fields: [
      { name: 'releasorName', label: 'Participant Name (Releasor)', placeholder: 'e.g., John Doe', type: 'text', required: true },
      { name: 'releaseeName', label: 'Organization Name (Releasee)', placeholder: 'e.g., Adventure Park Inc.', type: 'text', required: true },
      { name: 'activityDescription', label: 'Activity/Event Description', placeholder: 'e.g., Ziplining course', type: 'textarea', required: true },
      { name: 'dateOfActivity', label: 'Date of Activity', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'non-compete-agreement',
    name: 'Non-Compete Agreement',
    description: 'A contract in which an employee agrees not to compete with an employer after the employment period is over.',
    icon: 'FileLock',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., Tech Innovations Ltd.', type: 'text', required: true },
      { name: 'employeeName', label: 'Employee Name', placeholder: 'e.g., Mark Smith', type: 'text', required: true },
      { name: 'restrictedPeriod', label: 'Restricted Period (e.g., in months)', placeholder: 'e.g., 12', type: 'text', required: true },
      { name: 'geographicArea', label: 'Geographic Area of Restriction', placeholder: 'e.g., 50-mile radius of the company', type: 'text', required: true },
      { name: 'scopeOfRestriction', label: 'Scope of Restricted Activities', placeholder: 'e.g., Working for a direct competitor in the same industry', type: 'textarea', required: true },
    ],
  },
  {
    id: 'beta-test-agreement',
    name: 'Beta Test Agreement',
    description: 'An agreement for users who are testing a pre-release version of a product.',
    icon: 'FlaskConical',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., BetaSoftware Inc.', type: 'text', required: true },
      { name: 'testerName', label: 'Tester Name', placeholder: 'e.g., Emily White', type: 'text', required: true },
      { name: 'productName', label: 'Product Being Tested', placeholder: 'e.g., SuperApp Version 0.9', type: 'text', required: true },
      { name: 'testPeriod', label: 'Testing Period', placeholder: 'e.g., 30 days', type: 'text', required: true },
      { name: 'confidentialityClause', label: 'Confidentiality Obligations', placeholder: 'e.g., Tester agrees not to disclose information about the product.', type: 'textarea', required: true },
    ],
  },
  {
    id: 'influencer-agreement',
    name: 'Influencer Agreement',
    description: 'A contract between a brand and an influencer for marketing services.',
    icon: 'Megaphone',
    fields: [
      { name: 'brandName', label: 'Brand Name', placeholder: 'e.g., FashionForward Co.', type: 'text', required: true },
      { name: 'influencerName', label: 'Influencer Name', placeholder: 'e.g., @StyleGuru', type: 'text', required: true },
      { name: 'campaignDeliverables', label: 'Campaign Deliverables', placeholder: 'e.g., 2 Instagram posts, 1 YouTube video', type: 'textarea', required: true },
      { name: 'compensation', label: 'Compensation (Payment and/or Products)', placeholder: 'e.g., $1000 + free products', type: 'text', required: true },
      { name: 'campaignDates', label: 'Campaign Start and End Dates', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'equipment-rental-agreement',
    name: 'Equipment Rental Agreement',
    description: 'An agreement for renting equipment.',
    icon: 'Wrench',
    fields: [
      { name: 'ownerName', label: 'Equipment Owner Name', placeholder: 'e.g., EquipRentals LLC', type: 'text', required: true },
      { name: 'renterName', label: 'Renter Name', placeholder: 'e.g., Construction Pro', type: 'text', required: true },
      { name: 'equipmentDescription', label: 'Description of Equipment', placeholder: 'e.g., Bulldozer, Model XYZ', type: 'textarea', required: true },
      { name: 'rentalPeriod', label: 'Rental Period', placeholder: 'e.g., 1 week', type: 'text', required: true },
      { name: 'rentalFee', label: 'Rental Fee ($)', placeholder: 'e.g., 2000', type: 'text', required: true },
      { name: 'securityDeposit', label: 'Security Deposit ($)', placeholder: 'e.g., 500', type: 'text' },
    ],
  },
  {
    id: 'franchise-agreement',
    name: 'Franchise Agreement',
    description: 'A legal agreement that allows a franchisee to operate a business under the franchisor\'s brand.',
    icon: 'Store',
    fields: [
      { name: 'franchisorName', label: 'Franchisor Name', placeholder: 'e.g., Global Burger Corp.', type: 'text', required: true },
      { name: 'franchiseeName', label: 'Franchisee Name', placeholder: 'e.g., Local Eats LLC', type: 'text', required: true },
      { name: 'franchiseLocation', label: 'Franchise Location', placeholder: 'e.g., 123 Franchise Ln, Cityville', type: 'text', required: true },
      { name: 'franchiseFee', label: 'Initial Franchise Fee ($)', placeholder: 'e.g., 50000', type: 'text', required: true },
      { name: 'royaltyFee', label: 'Ongoing Royalty Fee (%)', placeholder: 'e.g., 5% of gross sales', type: 'text', required: true },
      { name: 'termOfAgreement', label: 'Term of Agreement (in years)', placeholder: 'e.g., 10', type: 'text', required: true },
    ],
  },
  {
    id: 'joint-venture-agreement',
    name: 'Joint Venture Agreement',
    description: 'An agreement between two or more parties to work together on a project.',
    icon: 'Handshake',
    fields: [
      { name: 'partyAName', label: 'Party A Name', placeholder: 'e.g., Company A', type: 'text', required: true },
      { name: 'partyBName', label: 'Party B Name', placeholder: 'e.g., Company B', type: 'text', required: true },
      { name: 'jvPurpose', label: 'Purpose of the Joint Venture', placeholder: 'e.g., To develop and market a new software product', type: 'textarea', required: true },
      { name: 'contributionsA', label: 'Contributions of Party A', placeholder: 'e.g., Capital, technology', type: 'textarea', required: true },
      { name: 'contributionsB', label: 'Contributions of Party B', placeholder: 'e.g., Marketing expertise, distribution channels', type: 'textarea', required: true },
      { name: 'profitSharingRatio', label: 'Profit Sharing Ratio', placeholder: 'e.g., 60% for Party A, 40% for Party B', type: 'text', required: true },
    ],
  },
  {
    id: 'settlement-agreement',
    name: 'Settlement Agreement',
    description: 'A legally binding contract that outlines the resolution of a dispute.',
    icon: 'Gavel',
    fields: [
      { name: 'party1Name', label: 'Party 1 Name', placeholder: 'e.g., Plaintiff Name', type: 'text', required: true },
      { name: 'party2Name', label: 'Party 2 Name', placeholder: 'e.g., Defendant Name', type: 'text', required: true },
      { name: 'disputeDescription', label: 'Description of the Dispute', placeholder: 'e.g., Breach of contract claim', type: 'textarea', required: true },
      { name: 'settlementAmount', label: 'Settlement Amount ($)', placeholder: 'e.g., 10000', type: 'text', required: true },
      { name: 'paymentTerms', label: 'Payment Terms', placeholder: 'e.g., Lump sum payment within 30 days', type: 'text', required: true },
      { name: 'dateOfAgreement', label: 'Date of Agreement', placeholder: '', type: 'date', required: true },
    ],
  },
  {
    id: 'shareholder-agreement',
    name: 'Shareholder Agreement',
    description: 'An arrangement among a company\'s shareholders that describes how the company should be operated.',
    icon: 'Building',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., Startup Innovations Inc.', type: 'text', required: true },
      { name: 'shareholder1Name', label: 'Shareholder 1 Name', placeholder: 'e.g., Shareholder A', type: 'text', required: true },
      { name: 'shareholder1Shares', label: 'Number of Shares for Shareholder 1', placeholder: 'e.g., 1000', type: 'text', required: true },
      { name: 'shareholder2Name', label: 'Shareholder 2 Name', placeholder: 'e.g., Shareholder B', type: 'text', required: true },
      { name: 'shareholder2Shares', label: 'Number of Shares for Shareholder 2', placeholder: 'e.g., 500', type: 'text', required: true },
      { name: 'decisionMakingProcess', label: 'Decision Making Process', placeholder: 'e.g., Majority vote, unanimous consent for major decisions', type: 'textarea', required: true },
    ],
  },
  {
    id: 'music-license-agreement',
    name: 'Music License Agreement',
    description: 'A legal agreement between a licensor and a licensee for the use of music.',
    icon: 'Music',
    fields: [
      { name: 'licensorName', label: 'Licensor Name (Music Owner)', placeholder: 'e.g., Artist or Record Label', type: 'text', required: true },
      { name: 'licenseeName', label: 'Licensee Name (User)', placeholder: 'e.g., Filmmaker, YouTuber', type: 'text', required: true },
      { name: 'songTitle', label: 'Song Title', placeholder: 'e.g., "My Hit Song"', type: 'text', required: true },
      { name: 'usageRights', label: 'Permitted Usage', placeholder: 'e.g., Background music for a YouTube video', type: 'textarea', required: true },
      { name: 'licenseFee', label: 'License Fee ($)', placeholder: 'e.g., 200', type: 'text', required: true },
      { name: 'territory', label: 'Territory of Use', placeholder: 'e.g., Worldwide', type: 'text', required: true },
    ],
  },
  {
    id: 'software-license-agreement',
    name: 'Software License Agreement',
    description: 'A legal instrument governing the use or redistribution of software.',
    icon: 'Code',
    fields: [
      { name: 'licensorName', label: 'Licensor Name (Software Owner)', placeholder: 'e.g., Tech Solutions LLC', type: 'text', required: true },
      { name: 'licenseeName', label: 'Licensee Name (User)', placeholder: 'e.g., End User Corp', type: 'text', required: true },
      { name: 'softwareName', label: 'Software Name and Version', placeholder: 'e.g., ProEditor v2.5', type: 'text', required: true },
      { name: 'licenseType', label: 'Type of License', placeholder: 'e.g., Perpetual, Subscription, Single-User', type: 'text', required: true },
      { name: 'usageRestrictions', label: 'Usage Restrictions', placeholder: 'e.g., Not for resale, no reverse engineering', type: 'textarea', required: true },
    ],
  },
  {
    id: 'referral-agreement',
    name: 'Referral Agreement',
    description: 'A contract that outlines the terms of a referral relationship.',
    icon: 'Users',
    fields: [
      { name: 'companyName', label: 'Company Name', placeholder: 'e.g., We Grow Businesses Inc.', type: 'text', required: true },
      { name: 'referrerName', label: 'Referrer Name', placeholder: 'e.g., John Referrer', type: 'text', required: true },
      { name: 'referralFee', label: 'Referral Fee/Commission', placeholder: 'e.g., 10% of the first sale, or $50 per qualified lead', type: 'text', required: true },
      { name: 'paymentConditions', label: 'Conditions for Payment', placeholder: 'e.g., Paid after the referred client signs a contract', type: 'textarea', required: true },
      { name: 'agreementTerm', label: 'Term of Agreement', placeholder: 'e.g., 1 year', type: 'text', required: true },
    ],
  },
  {
    id: 'event-sponsorship-agreement',
    name: 'Event Sponsorship Agreement',
    description: 'A contract between an event organizer and a sponsor.',
    icon: 'Calendar',
    fields: [
      { name: 'organizerName', label: 'Event Organizer Name', placeholder: 'e.g., Annual Tech Conference', type: 'text', required: true },
      { name: 'sponsorName', label: 'Sponsor Name', placeholder: 'e.g., Big Tech Corp', type: 'text', required: true },
      { name: 'eventName', label: 'Event Name and Date', placeholder: 'e.g., TechCon 2025, October 26-28', type: 'text', required: true },
      { name: 'sponsorshipLevel', label: 'Sponsorship Level', placeholder: 'e.g., Platinum, Gold', type: 'text', required: true },
      { name: 'sponsorshipFee', label: 'Sponsorship Fee ($)', placeholder: 'e.g., 25000', type: 'text', required: true },
      { name: 'sponsorBenefits', label: 'Sponsor Benefits', placeholder: 'e.g., Logo on all marketing materials, speaking slot', type: 'textarea', required: true },
    ],
  },
  {
    id: 'property-management-agreement',
    name: 'Property Management Agreement',
    description: 'An agreement between a property owner and a property manager.',
    icon: 'Building',
    fields: [
      { name: 'ownerName', label: 'Property Owner Name', placeholder: 'e.g., Jane Landlord', type: 'text', required: true },
      { name: 'managerName', label: 'Property Manager Name', placeholder: 'e.g., Pro Property Managers', type: 'text', required: true },
      { name: 'propertyAddress', label: 'Property Address', placeholder: 'e.g., 789 Property Lane', type: 'text', required: true },
      { name: 'managementFee', label: 'Management Fee', placeholder: 'e.g., 10% of monthly rent', type: 'text', required: true },
      { name: 'managerResponsibilities', label: 'Manager\'s Responsibilities', placeholder: 'e.g., Rent collection, maintenance, tenant screening', type: 'textarea', required: true },
    ],
  },
  {
    id: 'sublease-agreement',
    name: 'Sublease Agreement',
    description: 'An agreement where a tenant rents their room or apartment to another individual.',
    icon: 'Home',
    fields: [
      { name: 'originalTenantName', label: 'Original Tenant (Sublessor)', placeholder: 'e.g., Tenant A', type: 'text', required: true },
      { name: 'subtenantName', label: 'New Tenant (Sublessee)', placeholder: 'e.g., Tenant B', type: 'text', required: true },
      { name: 'landlordName', label: 'Landlord Name', placeholder: 'e.g., Building Owner', type: 'text', required: true },
      { name: 'propertyAddress', label: 'Property Address', placeholder: 'e.g., 123 Main St, Apt 4B', type: 'text', required: true },
      { name: 'subleaseStartDate', label: 'Sublease Start Date', placeholder: '', type: 'date', required: true },
      { name: 'subleaseEndDate', label: 'Sublease End Date', placeholder: '', type: 'date', required: true },
      { name: 'rentAmount', label: 'Monthly Rent ($)', placeholder: 'e.g., 1200', type: 'text', required: true },
    ],
  },
];
