'use client';

import { useState, useRef } from 'react';
import type { Template } from '@/lib/templates';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertTriangle, CheckCircle, Scale } from 'lucide-react';
import TemplateCard from './template-card';
import DraftForm from './draft-form';
import PricingCard from './pricing-card';
import { Button } from '@/components/ui/button';

type LegalDraftingWizardProps = {
  templates: Template[];
};

export default function LegalDraftingWizard({ templates }: LegalDraftingWizardProps) {
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [showAllTemplates, setShowAllTemplates] = useState(false);
  const draftFormRef = useRef<HTMLDivElement>(null);

  const handleSelectTemplate = (template: Template) => {
    setSelectedTemplate(template);
    setTimeout(() => {
      draftFormRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  };

  const displayedTemplates = showAllTemplates ? templates : templates.slice(0, 8);

  const pricingTiers = [
    {
      title: 'Free',
      price: '$0',
      period: '',
      features: ['3 free legal drafts', 'Access to all templates', 'Standard support'],
      buttonText: 'Get Started',
      variant: 'secondary' as const,
    },
    {
      title: 'Pro',
      price: '$19.99',
      period: '/month',
      features: ['50 drafts per month', 'Access to all templates', 'Priority support', 'Download in multiple formats'],
      buttonText: 'Upgrade to Pro',
      variant: 'default' as const,
      highlight: true,
      priceId: 'price_placeholder_pro',
    },
    {
      title: 'Agency',
      price: '$49.99',
      period: '/month',
      features: ['Unlimited drafts', 'Access to all templates', 'Dedicated 24/7 support', 'Team access (up to 5 users)'],
      buttonText: 'Contact Sales',
      variant: 'secondary' as const,
      priceId: 'price_placeholder_agency',
    },
  ];

  return (
    <div className="container mx-auto px-4 py-8 md:py-16">
      {/* Hero Section */}
      <section className="text-center mb-16">
        <div className="inline-block bg-primary/10 p-4 rounded-full mb-4">
          <Scale className="h-10 w-10 text-primary" />
        </div>
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-4">
          AI-Powered Legal Documents
        </h1>
        <p className="max-w-3xl mx-auto text-lg md:text-xl text-muted-foreground mb-8">
          Generate professional legal agreements and contracts in minutes. Just select a template, fill in the details, and let our AI do the rest.
        </p>
      </section>

      {/* Disclaimer */}
      <section className="max-w-4xl mx-auto mb-16">
        <Alert variant="destructive" className="bg-destructive/5 border-destructive/20 text-destructive-foreground">
          <AlertTriangle className="h-4 w-4 !text-destructive" />
          <AlertTitle className="text-destructive font-semibold">Important Disclaimer</AlertTitle>
          <AlertDescription>
            The documents generated by Legal Draft AI are for informational purposes only and do not constitute legal advice. Please consult with a qualified attorney to review your document before execution.
          </AlertDescription>
        </Alert>
      </section>

      {/* Template Selection */}
      <section id="templates" className="mb-16">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight">1. Choose Your Template</h2>
          <p className="text-muted-foreground mt-2">Select from our library of {templates.length} templates.</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {displayedTemplates.map((template) => (
            <TemplateCard
              key={template.id}
              template={template}
              onSelect={() => handleSelectTemplate(template)}
            />
          ))}
        </div>
        {templates.length > 8 && (
          <div className="text-center mt-8">
            <Button onClick={() => setShowAllTemplates(!showAllTemplates)}>
              {showAllTemplates ? 'Show Less' : 'Show More'}
            </Button>
          </div>
        )}
      </section>

      {/* AI Drafting Form */}
      <div ref={draftFormRef} className="scroll-mt-20">
        {selectedTemplate && (
          <section id="draft" className="mb-16 transition-all duration-500 ease-in-out">
            <DraftForm template={selectedTemplate} onClear={() => setSelectedTemplate(null)} />
          </section>
        )}
      </div>

      {/* Pricing Section */}
      <section id="pricing" className="py-16 bg-card rounded-xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight">Simple, Transparent Pricing</h2>
          <p className="text-muted-foreground mt-2">Choose the plan that&apos;s right for you.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          {pricingTiers.map((tier) => (
            <PricingCard key={tier.title} {...tier} />
          ))}
        </div>
      </section>
    </div>
  );
}
