import Header from "@/components/header";
import Footer from "@/components/footer";

export default function TermsOfServicePage() {
  return (
    <div className="flex flex-col min-h-dvh">
      <Header />
      <main className="flex-1">
        <div className="container mx-auto px-4 py-8 md:py-16">
          <div className="prose lg:prose-xl mx-auto">
            <h1>Terms of Service</h1>
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

            <h2>1. Introduction</h2>
            <p>
              Welcome to Legal Draft AI (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). These Terms of
              Service (&quot;Terms&quot;) govern your use of our website and the services we
              provide. By accessing or using our service, you agree to be bound
              by these Terms.
            </p>

            <h2>2. Use of Our Service</h2>
            <p>
              You must be at least 18 years old to use our service. You are
              responsible for any activity that occurs through your account and
              you agree you will not sell, transfer, license or assign your
              account, username, or any account rights.
            </p>
             <p>
              The documents generated by Legal Draft AI are for informational purposes only and do not constitute legal advice. You should consult with a qualified attorney to review your document before execution. We are not a law firm and do not provide legal advice.
            </p>

            <h2>3. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality
              are and will remain the exclusive property of Legal Draft AI and its
              licensors.
            </p>

            <h2>4. Termination</h2>
            <p>
              We may terminate or suspend your account immediately, without prior
              notice or liability, for any reason whatsoever, including without
              limitation if you breach the Terms.
            </p>

            <h2>5. Limitation of Liability</h2>
            <p>
              In no event shall Legal Draft AI, nor its directors, employees,
              partners, agents, suppliers, or affiliates, be liable for any
              indirect, incidental, special, consequential or punitive damages,
              including without limitation, loss of profits, data, use,
              goodwill, or other intangible losses, resulting from your access
              to or use of or inability to access or use the Service.
            </p>

            <h2>6. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the
              laws of the jurisdiction in which our company is established,
              without regard to its conflict of law provisions.
            </p>

            <h2>7. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace
              these Terms at any time. We will provide at least 30 days' notice
              prior to any new terms taking effect.
            </p>

            <h2>8. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
